config/routes.rb
Rails.application.routes.draw do
	
  
  #devise_for :models
  devise_for :users
  root :to => 'home#index'
  
  

  match '/get_division', controller: 'admin/areas', action: 'get_division', via: [:get], as: 'get_division'
  
  match '/find_station', controller: 'admin/rake_loads', action: 'find_station', via: [:get], as: 'find_station'
  match '/find_from_station', controller: 'admin/rake_loads', action: 'find_from_station', via: [:get], as: 'find_from_station'
  match '/delete_rake_load', controller: 'admin/rake_loads', action: 'delete_rake_load', via: [:get], as: 'delete_rake_load'
  
  match '/find_to_station_other_loads', controller: 'admin/other_loads', action: 'find_to_station_other_loads', via: [:get], as: 'find_to_station_other_loads'
  match '/find_from_station_other_loads', controller: 'admin/other_loads', action: 'find_from_station_other_loads', via: [:get], as: 'find_from_station_other_loads'
  match '/delete_other_load', controller: 'admin/other_loads', action: 'delete_other_load', via: [:get], as: 'delete_other_load'
  
  match '/load_commodity_breakup', controller: 'admin/one_rake_loads', action: 'load_commodity_breakup', via: [:get], as: 'load_commodity_breakup'
  match '/delete_rake_commodity_breakup', controller: 'admin/one_rake_loads', action: 'delete_rake_commodity_breakup', via: [:get], as: 'delete_rake_commodity_breakup'  

  match '/unload_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'unload_commodity_breakup', via: [:get], as: 'unload_commodity_breakup'
  match '/delete_unload_rake_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'delete_unload_rake_commodity_breakup', via: [:get], as: 'delete_unload_rake_commodity_breakup'

  match '/find_station_unloads', controller: 'admin/rake_unloads', action: 'find_station_unloads', via: [:get], as: 'find_station_unloads'
  match '/find_from_station_unloads', controller: 'admin/rake_unloads', action: 'find_from_station_unloads', via: [:get], as: 'find_from_station_unloads'
  match '/delete_rake_unload', controller: 'admin/rake_unloads', action: 'delete_rake_unload', via: [:get], as: 'delete_rake_unload'
  
  match '/find_to_station_other_unloads', controller: 'admin/other_unloads', action: 'find_to_station_other_unloads', via: [:get], as: 'find_to_station_other_unloads'
  match '/find_from_station_other_unloads', controller: 'admin/other_unloads', action: 'find_from_station_other_unloads', via: [:get], as: 'find_from_station_other_unloads'
  match '/delete_other_unload', controller: 'admin/other_unloads', action: 'delete_other_unload', via: [:get], as: 'delete_other_unload'
  

  match '/find_to_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_to_station_gets_unloads', via: [:get], as: 'find_to_station_gets_unloads'
  match '/find_from_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_from_station_gets_unloads', via: [:get], as: 'find_from_station_gets_unloads'
  match '/delete_gets_unload', controller: 'admin/gets_unloads', action: 'delete_gets_unload', via: [:get], as: 'delete_gets_unload'
  
  match '/find_to_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_to_station_aecs_unloads', via: [:get], as: 'find_to_station_aecs_unloads'
  match '/find_from_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_from_station_aecs_unloads', via: [:get], as: 'find_from_station_aecs_unloads'
  match '/delete_aecs_unload', controller: 'admin/aecs_unloads', action: 'delete_aecs_unload', via: [:get], as: 'delete_aecs_unload'

  match '/delete_load_interchange', controller: 'admin/load_interchanges', action: 'delete_load_interchange', via: [:get], as: 'delete_load_interchange'
  match '/delete_crack_rake', controller: 'admin/crack_rakes', action: 'delete_crack_rake', via: [:get], as: 'delete_crack_rake'
  
  match '/delete_allowance', controller: 'admin/allowances', action: 'delete_allowance', via: [:get], as: 'delete_allowance'
  
  match '/delete_employee_allowance', controller: 'admin/employee_allowances', action: 'delete_employee_allowance', via: [:get], as: 'delete_employee_allowance'
  
  match '/delete_employee', controller: 'admin/employees', action: 'delete_employee', via: [:get], as: 'delete_employee'
  match '/delete_employee_category_detail', controller: 'admin/employees', action: 'delete_employee_category_detail', via: [:get], as: 'delete_employee_category_detail'
  match '/delete_employee_transfer_detail', controller: 'admin/employees', action: 'delete_employee_transfer_detail', via: [:get], as: 'delete_employee_transfer_detail'
  match '/delete_employee_training_detail', controller: 'admin/employees', action: 'delete_employee_training_detail', via: [:get], as: 'delete_employee_training_detail'
  match '/delete_employee_medical_detail', controller: 'admin/employees', action: 'delete_employee_medical_detail', via: [:get], as: 'delete_employee_medical_detail'
  match '/delete_employee_dar_detail', controller: 'admin/employees', action: 'delete_employee_dar_detail', via: [:get], as: 'delete_employee_dar_detail'
  match '/delete_employee_award_detail', controller: 'admin/employees', action: 'delete_employee_award_detail', via: [:get], as: 'delete_employee_award_detail'
  match '/find_employee_number', controller: 'admin/employees', action: 'find_employee_number', via: [:get], as: 'find_employee_number'
  
  match '/delete_employee_cadre', controller: 'admin/employee_cadres', action: 'delete_employee_cadre', via: [:get], as: 'delete_employee_cadre'
  

  #--------------Excel Reports Download Starts-----------------
  match '/rake_load_excel_download', controller: 'admin/loading_reports', action: 'rake_load_excel_download', via: [:get], as: 'rake_load_excel_download'
  match '/custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'custom_load_report_excel_download', via: [:get], as: 'custom_load_report_excel_download'
  match '/month_custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'month_custom_load_report_excel_download', via: [:get], as: 'month_custom_load_report_excel_download'
  match '/excel_reports_download', controller: 'admin/excel_reports', action: 'excel_reports_download', via: [:get], as: 'excel_reports_download'
  

  #--------------Excel Reports Download Ends-----------------

  #--------------PDF Reports Download Starts-----------------
  match '/download_summary_pdf', controller: 'admin/loading_reports', action: 'download_summary_pdf', via: [:get], as: 'download_summary_pdf'
  match '/abc_unload_summary_pdf', controller: 'admin/unloading_reports', action: 'abc_unload_summary_pdf', via: [:get], as: 'abc_unload_summary_pdf'
  #--------------PDF Reports Download Ends-----------------

  namespace :admin do
  	resources :railway_zones,:states,:divisions, :areas,:stations,:rake_commodities,:major_commodities, :wagon_types, :load_unloads, :rake_loads, :rake_unloads, :other_loads, :one_rake_loads, :two_rake_loads, :one_rake_unloads, :other_unloads, :gets_unloads, :aecs_unloads, :short_routes, :ic_divisions, :users, :user_roles, :loading_reports,:unloading_reports, :phasewise_reports, :one_loading_reports, :one_unloading_reports, :custom_reports, :one_custom_reports, :custom_load_reports, :month_rake_loads, :two_custom_reports, :load_interchanges, :excel_reports, :crack_rakes, :daks, :ti_positions, :allowances, :employees, :employee_cadres, :employee_allowances, :station_datas
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/aecs_unloads_controller.rb
class Admin::AecsUnloadsController < ApplicationController
  layout "admin/application"

  def index
    # @aecs_unloads = RakeUnload.all.where(:form_status => "AECS")
  end
  

  def show
    
  end

  def new
    data = params[:data].to_date if params[:data].present?
    data = Date.today if data.blank?
    @aecs_unloads = RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq(data).and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    @aecs_unloads += RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq(nil).and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    @aecs_unloads += RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq("").and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    rake_and_unit_array = RakeUnload.where(release_date: data,form_status: "AECS").pluck(:loaded_unit, :rake_count)
    @total_unit_aecs_unloads = rake_and_unit_array.collect(&:first).sum
    @total_rake_aecs_unloads = rake_and_unit_array.collect(&:second).sum

    get_data_for_form
  end

  def create
    RakeUnload.create_or_update_aecs_unload(params)

    data = params["date"].to_date if params["date"].present?
    data = Date.today if data.blank?

    @aecs_unloads = RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq(data).and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    @aecs_unloads += RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq(nil).and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    @aecs_unloads += RakeUnload.where(RakeUnload.arel_table[:takenover_date].lteq(data).and(RakeUnload.arel_table[:release_date].eq("").and(RakeUnload.arel_table[:form_status].eq("AECS"))))
    rake_and_unit_array = RakeUnload.where(release_date: data,form_status: "AECS").pluck(:loaded_unit, :rake_count)
    @total_unit_aecs_unloads = rake_and_unit_array.collect(&:first).sum if rake_and_unit_array.present?
    @total_rake_aecs_unloads = rake_and_unit_array.collect(&:second).sum if rake_and_unit_array.present?

    get_data_for_form
  end

  def get_data_for_form
    @major_commodity = MajorCommodity.all.map{|major|[major.major_commodity,major.id]}
    @wagon_type = WagonType.where(is_viewable: true).order(wagon_type_code: :asc).map{|wagon| ["#{wagon.wagon_type_code}--#{wagon.wagon_type_desc}",wagon.id]}
    @rake_commodity = {}
    MajorCommodity.includes(:rake_commodities).each do |major|
    rake_commodity_array = major.rake_commodities.map{|rake_commodity| ["#{rake_commodity.rake_commodity_code}-#{rake_commodity.rake_commodity_name}",rake_commodity.id]}
      @rake_commodity[major.id] = {data: rake_commodity_array}
    end
  end  

   def find_to_station_aecs_unloads # finds to station
    
    station_code = params[:station_code]
    @to_station = params[:to_station_id]
    to_station_code_id = Station.where(code: station_code).pluck(:id)
    @stn = LoadUnload.find_by(station_id: to_station_code_id)? true : false
    # @stn = Station.find_by(code: station_code)? true : false
        
      respond_to do |format|
        format.js
      end
    
  end

  def find_from_station_aecs_unloads  # finds from station
    
    from_station_code = params[:from_station_code]
    @from_station = params[:from_station_id]
    @stn = Station.find_by(code: from_station_code)? true : false
    
      respond_to do |format|
        format.js
      end
    
  end  

  def delete_aecs_unload
    
    delete_rake_id = params[:delete_rake_id]
    id = delete_rake_id.to_i
    RakeUnload.destroy(id)
    
      respond_to do |format|
        format.js
      end
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end
end

app/helpers/admin/aecs_unloads_helper.rb
module Admin::AecsUnloadsHelper
end

app/views/admin/aecs_unloads/_aecs_unload_new.html.erb
<div class="tab-container" id="aecs_unload_form">
  <div class="tab-content" >
    <%= render 'form' %>
  </div>
</div>

app/views/admin/aecs_unloads/create.js.erb
$("#aecs_unload_form").remove('');
$("#aecs_unload_new_form").html('<%= j render 'aecs_unload_new'%>');
$('.release_date').each(function(i) {
  var row_no = $(this).attr('id').split('_')[2]
  var release_date_id = "#release_date_"+row_no
  var mydate = $("#datepicker").val();
  var parts = mydate.split('/');
  var setreleasedate = parts[2] + '-' + parts[1] + '-' + parts[0];
  $(release_date_id).attr("max", setreleasedate);
  $(release_date_id).attr("min", setreleasedate);
});

app/views/admin/aecs_unloads/find_from_station_aecs_unloads.js.erb
var from_station = "#<%=@from_station%>"
<%if(@stn == false)%>

  var error_msg ="----From Station not found"
  $("#station_error_msg").text(error_msg).css({'color': 'red', 'background-color': 'yellow', 'width':'170px'});
  $(".station_error_msg").show();
  $(from_station).focus(); 
  
<%else%>
  $("#station_error_msg").text("");
  $(".station_error_msg").hide();
<%end%>

app/views/admin/aecs_unloads/find_to_station_aecs_unloads.js.erb
var to_station = "#<%=@to_station%>"
<%if(@stn == false)%>

  var error_msg ="-----To Station not found"
  $("#station_error_msg").text(error_msg).css({'color': 'red', 'background-color': 'yellow', 'width':'170px'});
  $(".station_error_msg").show();
  $(to_station).focus(); 
<%else%>
 $(".station_error_msg").hide();
<%end%>

app/views/admin/aecs_unloads/index.html.erb
<script>

    $(document).ready(function () {
      $('.sidebar-remain-open').click();
    });

</script>

app/views/admin/aecs_unloads/new.html.erb
<script>

    $(document).ready(function () {
      $('.loading-remain-open').click();
    });

</script>
<style>
  .modal-dialog {
      margin: 30px auto;
      width: 80%;
  }
  .add-cursor tr{
   height: 5px;
  }  
  .table.table-dark tbody td {
    padding: 5px;

  }

.add-cursor {cursor: pointer;}
.add-cursor span {cursor: pointer;display: inline-block;position: relative;transition: 0.5s;}
/*.tax-and-statutory-settings-hide-show span:after {content: '»';position: absolute;opacity: 0;top: 0;right: -20px;transition: 0.5s;}
.tax-and-statutory-settings-hide-show span {padding-right: 25px;}
.tax-and-statutory-settings-hide-show:hover span:after {opacity: 1;right: 0;}*/
.input-group .form-control {
    float: right;
    width: 35%;
  }
  html {
    overflow-x: scroll;
  }

  select.set-dropdown {
    display: block !important;
    opacity: 0;
    height: 0px;
  }
  table th, table td { overflow: hidden; }
  
  
</style>


<% @method = params[:id].present? ? "PATCH" : "POST" %>
<% @url = params[:id].present? ? admin_aecs_unload_path(params[:id]) : admin_aecs_unloads_path %>


<div class="table-responsive main-client-ldng" >
  <div id="client-message"></div>
  <table class="table hover table-dark" id="aecs_unload-unldng">
    <caption>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
          <span class="pull-left lead-text">
            AECS Un-Loading 
          </span>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
        <%= text_field_tag "aecs_unload_date", Date.today.strftime('%Y-%m-%d'),placeholder: 'rake unload date', id: "datepicker", class: 'form-control input_class'%>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
        <button class="btn btn-primary btn-flat submit_data" id="submit_data" type="submit">Display</button>
      </div>
  </caption>
  </table>
  </div>


<div id="aecs_unload_new_form"></div>
<script>
  var old_date = '<%=Date.today.strftime("%d/%m/%Y")%>';
  $(function () {
    $("#datepicker").datepicker({ 
          autoclose: true, 
          format:"dd/mm/yyyy",
          todayHighlight: true,
    });

    $("#datepicker").on("change",function(){
      $("#aecs_unload_new_form").empty();
    });

    $('#datepicker').datepicker('setDate', 'today');

  });

  $(".submit_data").click(function () {
      
      effective_from = $("#datepicker").val();
      // if(old_date != effective_from){
        $.ajax({
          type: "get",
          url: "/admin/aecs_unloads/new.js?data=" + effective_from
        });
      //   old_date = effective_from 
      // }
  });
    
  

  

</script>

app/views/admin/aecs_unloads/new.js.erb
$("#aecs_unload_form").remove('');
$("#aecs_unload_new_form").html('<%= j render 'aecs_unload_new'%>');
$('.release_date').each(function(i) {
  var row_no = $(this).attr('id').split('_')[2]
  var release_date_id = "#release_date_"+row_no
  var mydate = $("#datepicker").val();
  var parts = mydate.split('/');
  var setreleasedate = parts[2] + '-' + parts[1] + '-' + parts[0];
  $(release_date_id).attr("max", setreleasedate);
  $(release_date_id).attr("min", setreleasedate);
});