config/routes.rb
Rails.application.routes.draw do
	
  
  #devise_for :models
  devise_for :users
  root :to => 'home#index'
  
  

  match '/get_division', controller: 'admin/areas', action: 'get_division', via: [:get], as: 'get_division'
  
  match '/find_station', controller: 'admin/rake_loads', action: 'find_station', via: [:get], as: 'find_station'
  match '/find_from_station', controller: 'admin/rake_loads', action: 'find_from_station', via: [:get], as: 'find_from_station'
  match '/delete_rake_load', controller: 'admin/rake_loads', action: 'delete_rake_load', via: [:get], as: 'delete_rake_load'
  
  match '/find_to_station_other_loads', controller: 'admin/other_loads', action: 'find_to_station_other_loads', via: [:get], as: 'find_to_station_other_loads'
  match '/find_from_station_other_loads', controller: 'admin/other_loads', action: 'find_from_station_other_loads', via: [:get], as: 'find_from_station_other_loads'
  match '/delete_other_load', controller: 'admin/other_loads', action: 'delete_other_load', via: [:get], as: 'delete_other_load'
  
  match '/load_commodity_breakup', controller: 'admin/one_rake_loads', action: 'load_commodity_breakup', via: [:get], as: 'load_commodity_breakup'
  match '/delete_rake_commodity_breakup', controller: 'admin/one_rake_loads', action: 'delete_rake_commodity_breakup', via: [:get], as: 'delete_rake_commodity_breakup'  

  match '/unload_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'unload_commodity_breakup', via: [:get], as: 'unload_commodity_breakup'
  match '/delete_unload_rake_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'delete_unload_rake_commodity_breakup', via: [:get], as: 'delete_unload_rake_commodity_breakup'

  match '/find_station_unloads', controller: 'admin/rake_unloads', action: 'find_station_unloads', via: [:get], as: 'find_station_unloads'
  match '/find_from_station_unloads', controller: 'admin/rake_unloads', action: 'find_from_station_unloads', via: [:get], as: 'find_from_station_unloads'
  match '/delete_rake_unload', controller: 'admin/rake_unloads', action: 'delete_rake_unload', via: [:get], as: 'delete_rake_unload'
  
  match '/find_to_station_other_unloads', controller: 'admin/other_unloads', action: 'find_to_station_other_unloads', via: [:get], as: 'find_to_station_other_unloads'
  match '/find_from_station_other_unloads', controller: 'admin/other_unloads', action: 'find_from_station_other_unloads', via: [:get], as: 'find_from_station_other_unloads'
  match '/delete_other_unload', controller: 'admin/other_unloads', action: 'delete_other_unload', via: [:get], as: 'delete_other_unload'
  

  match '/find_to_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_to_station_gets_unloads', via: [:get], as: 'find_to_station_gets_unloads'
  match '/find_from_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_from_station_gets_unloads', via: [:get], as: 'find_from_station_gets_unloads'
  match '/delete_gets_unload', controller: 'admin/gets_unloads', action: 'delete_gets_unload', via: [:get], as: 'delete_gets_unload'
  
  match '/find_to_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_to_station_aecs_unloads', via: [:get], as: 'find_to_station_aecs_unloads'
  match '/find_from_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_from_station_aecs_unloads', via: [:get], as: 'find_from_station_aecs_unloads'
  match '/delete_aecs_unload', controller: 'admin/aecs_unloads', action: 'delete_aecs_unload', via: [:get], as: 'delete_aecs_unload'

  match '/delete_load_interchange', controller: 'admin/load_interchanges', action: 'delete_load_interchange', via: [:get], as: 'delete_load_interchange'
  match '/delete_crack_rake', controller: 'admin/crack_rakes', action: 'delete_crack_rake', via: [:get], as: 'delete_crack_rake'
  
  match '/delete_allowance', controller: 'admin/allowances', action: 'delete_allowance', via: [:get], as: 'delete_allowance'
  
  match '/delete_employee_allowance', controller: 'admin/employee_allowances', action: 'delete_employee_allowance', via: [:get], as: 'delete_employee_allowance'
  
  match '/delete_employee', controller: 'admin/employees', action: 'delete_employee', via: [:get], as: 'delete_employee'
  match '/delete_employee_category_detail', controller: 'admin/employees', action: 'delete_employee_category_detail', via: [:get], as: 'delete_employee_category_detail'
  match '/delete_employee_transfer_detail', controller: 'admin/employees', action: 'delete_employee_transfer_detail', via: [:get], as: 'delete_employee_transfer_detail'
  match '/delete_employee_training_detail', controller: 'admin/employees', action: 'delete_employee_training_detail', via: [:get], as: 'delete_employee_training_detail'
  match '/delete_employee_medical_detail', controller: 'admin/employees', action: 'delete_employee_medical_detail', via: [:get], as: 'delete_employee_medical_detail'
  match '/delete_employee_dar_detail', controller: 'admin/employees', action: 'delete_employee_dar_detail', via: [:get], as: 'delete_employee_dar_detail'
  match '/delete_employee_award_detail', controller: 'admin/employees', action: 'delete_employee_award_detail', via: [:get], as: 'delete_employee_award_detail'
  match '/find_employee_number', controller: 'admin/employees', action: 'find_employee_number', via: [:get], as: 'find_employee_number'
  
  match '/delete_employee_cadre', controller: 'admin/employee_cadres', action: 'delete_employee_cadre', via: [:get], as: 'delete_employee_cadre'
  

  #--------------Excel Reports Download Starts-----------------
  match '/rake_load_excel_download', controller: 'admin/loading_reports', action: 'rake_load_excel_download', via: [:get], as: 'rake_load_excel_download'
  match '/custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'custom_load_report_excel_download', via: [:get], as: 'custom_load_report_excel_download'
  match '/month_custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'month_custom_load_report_excel_download', via: [:get], as: 'month_custom_load_report_excel_download'
  match '/excel_reports_download', controller: 'admin/excel_reports', action: 'excel_reports_download', via: [:get], as: 'excel_reports_download'
  

  #--------------Excel Reports Download Ends-----------------

  #--------------PDF Reports Download Starts-----------------
  match '/download_summary_pdf', controller: 'admin/loading_reports', action: 'download_summary_pdf', via: [:get], as: 'download_summary_pdf'
  match '/abc_unload_summary_pdf', controller: 'admin/unloading_reports', action: 'abc_unload_summary_pdf', via: [:get], as: 'abc_unload_summary_pdf'
  #--------------PDF Reports Download Ends-----------------

  namespace :admin do
  	resources :railway_zones,:states,:divisions, :areas,:stations,:rake_commodities,:major_commodities, :wagon_types, :load_unloads, :rake_loads, :rake_unloads, :other_loads, :one_rake_loads, :two_rake_loads, :one_rake_unloads, :other_unloads, :gets_unloads, :aecs_unloads, :short_routes, :ic_divisions, :users, :user_roles, :loading_reports,:unloading_reports, :phasewise_reports, :one_loading_reports, :one_unloading_reports, :custom_reports, :one_custom_reports, :custom_load_reports, :month_rake_loads, :two_custom_reports, :load_interchanges, :excel_reports, :crack_rakes, :daks, :ti_positions, :allowances, :employees, :employee_cadres, :employee_allowances, :station_datas
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/other_loads_controller.rb
class Admin::OtherLoadsController < ApplicationController
  layout "admin/application"

  def index
  
  end
  

  def show
    
  end

  def new
    data = params[:data].to_date if params[:data].present?
    data = Date.today if data.blank?
    @other_loads = RakeLoad.where(release_date: data,rakeform_otherform: "O")

    current_user_other_load = []
      @other_loads.each do |other_load|
        rake_area =  other_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          current_user_other_load << other_load
        end
      end
    @other_loads = current_user_other_load

    @total_rake_loads = (RakeLoad.where(release_date: data,rakeform_otherform: "R"))
      load_unit = 0
      @total_rake_loads.each do |total_rake_load|
        rake_area =  total_rake_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          load_unit = load_unit+total_rake_load.loaded_unit
        end
      end
    @total_rake_loads = load_unit
    
    @total_other_loads = (RakeLoad.where(release_date: data,rakeform_otherform: "O"))
      load_unit = 0
      @total_other_loads.each do |total_other_load|
        rake_area =  total_other_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          load_unit = load_unit+total_other_load.loaded_unit
        end
      end
    @total_other_loads = load_unit

    get_data_for_form
  end

  def get_data_for_form
    @major_commodity = MajorCommodity.all.map{|major|[major.major_commodity,major.id]}
    @wagon_type = WagonType.where(is_viewable: true).map{|wagon| [wagon.wagon_type_code,wagon.id]}
    @rake_commodity = {}
    MajorCommodity.includes(:rake_commodities).each do |major|
    rake_commodity_array = major.rake_commodities.map{|rake_commodity| ["#{rake_commodity.rake_commodity_code}-#{rake_commodity.rake_commodity_name}",rake_commodity.id]}
      @rake_commodity[major.id] = {data: rake_commodity_array}
    end
  end  

  
  def create
    RakeLoad.create_or_update_other_load(params)
    data = params[:date].to_date if params[:date].present?
    data = Date.today if data.blank?
    @other_loads = RakeLoad.where(release_date: data,rakeform_otherform: "O")
    
    current_user_other_load = []
      @other_loads.each do |other_load|
        rake_area =  other_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          current_user_other_load << other_load
        end
      end
    @other_loads = current_user_other_load

    @total_rake_loads = (RakeLoad.where(release_date: data,rakeform_otherform: "R"))
      load_unit = 0
      @total_rake_loads.each do |total_rake_load|
        rake_area =  total_rake_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          load_unit = load_unit+total_rake_load.loaded_unit
        end
      end
    @total_rake_loads = load_unit
    
    @total_other_loads = (RakeLoad.where(release_date: data,rakeform_otherform: "O"))
      load_unit = 0
      @total_other_loads.each do |total_other_load|
        rake_area =  total_other_load.load_unload.station.area.area_code rescue nil
        current_user_area = current_user.area rescue nil
        
        if rake_area == current_user_area
          load_unit = load_unit+total_other_load.loaded_unit
        end
      end
    @total_other_loads = load_unit
    get_data_for_form

  end

  def find_to_station_other_loads # finds to station
    
    station_code = params[:station_code]
    @to_station = params[:to_station_id]
    @stn = Station.find_by(code: station_code)? true : false
        
      respond_to do |format|
        format.js
      end
    
  end

  def find_from_station_other_loads
    
    get_user_area

    from_station_code = params[:from_station_code]
    @from_station = params[:from_station_id]
    from_station_code_id = Station.where(code: from_station_code).pluck(:id)
    @stn = LoadUnload.find_by(station_id: from_station_code_id, area_id: @user_area_id)? true : false
    
      respond_to do |format|
        format.js
      end
    
  end

  def get_user_area
    user_area = current_user.area
    if user_area.present? 
      @user_area_id = Area.where(area_code: user_area).pluck(:id)
    end 
    
  end

  def delete_other_load
    delete_other_load_id = params[:delete_other_load_id]
    id = delete_other_load_id.to_i
    RakeLoad.destroy(id)
   
      respond_to do |format|
        format.js
      end
  end

  def edit
    get_data_for_form
  end

  def update
    
  end

  def destroy
    
  end
end

app/helpers/admin/other_loads_helper.rb
module Admin::OtherLoadsHelper
end

app/views/admin/other_loads/_form.html.erb
<% @method = "POST" %>
<% @url = admin_other_loads_path %>
<div class="table-responsive" style="overflow-x: scroll; overflow-y: scroll;">
  <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" >
    <p style="font-size: 20px;color:red;">Total-Loading :<%=(@total_rake_loads)+(@total_other_loads)%>&nbsp;&nbsp;&nbsp;
        Rake-:<%=(@total_rake_loads)%>&nbsp;&nbsp;&nbsp;
        Other-:<%=(@total_other_loads)%>
    
    </p>
  </div>
<%= form_tag(@url, method: @method, class: 'form-horizontal', id: 'other-loading-form',remote: true) do |form| %>
<table class="table hover table-dark span12" style="margin-bottom: 20px !important; overflow-x: scroll; ">
  <thead>
  <tr>

    <th>SR NO</th>
    <th>From_Station To_Station</th>
    <th>Loaded_Unit RakeCount</th>
    <th>Commodity Wagon_Type</th>
    <th>GrossTons NetTons</th>
    <th>ODR_Type<br> ODR_Date</th>
    <th>Release Time-Date</th>
    <th>Remarks</th>
    <th>Action</th>
    
  </tr>
  </thead>
  <tbody>
    
      <%(0..25).each_with_index do |no, index| %>

       <tr class="other-load-tr other-row-data other_load_row_<%= index %>", id= "other_load_row_id_<%= index %>">

        <td align="center" style="font-size: 25;">
        </td>
        <td>
          <%= text_field_tag "from_station_#{index}", '',placeholder: 'FromSTN', id: "from_station_#{index}", class: 'form-control input-md from_station',maxlength:"4", required: true, style: "width: 85px; font-size:16px; text-transform:uppercase;"%>
        <p></p>
          
          <%= text_field_tag "to_station_#{index}", '',placeholder: 'To STN', id: "to_station_#{index}", class: 'form-control input-md to_station',maxlength:"4", required: true, style: "width: 85px; font-size:16px; text-transform:uppercase;"%>
        </td>
        <td>
          <%= number_field_tag "loaded_unit_#{index}", '', placeholder: "L", class: 'form-control input-md',title: 'Enter loaded Units', id: "loaded_unit_#{index}",required: true, style: "width: 75px; font-size:16px;" %>
        <p></p>
          <%= number_field_tag "rake_count_#{index}",'', placeholder: "Count", class: 'form-control input-md',id: "rake_count_#{index}",required: true,min:"0", max: "1", style: "width: 75px;border: 1px solid #888;" %>
        </td>
        <td>
          <%= select_tag "major_commodity_#{index}", options_for_select(@major_commodity), {prompt: "Commodity", class: 'form-control input-md',required: true, style: "width: 110px;", id: "major_commodity_#{index}",data_live_search: "true"} %>
        <p></p>
          <%= select_tag "wagon_type_#{index}", options_for_select(@wagon_type), {prompt: "Stock", class: 'form-control input-md',required: true, style: "width: 110px;", id: "wagon_type_#{index}", data_live_search: "true"} %>
        </td>
        <td>
          <%= number_field_tag "gross_tons_#{index}", '',placeholder: 'Gross', id: "gross_tons_#{index}", class: 'form-control input-md', style: "width: 80px; font-size:16px;"%>
        <p></p>
          <%= number_field_tag "net_tons_#{index}", '',placeholder: 'Net', id: "net_tons_#{index}", class: 'form-control input-md', style: "width: 80px; font-size:16px;"%>
        </td>
        
        <td>
          <%= select_tag "odr_type_#{index}", options_for_select([["A","A"],["B","B"],["C","C"],["D","D"],["E","E"]]), {prompt: "ODR", class: 'form-control input-md', required: true, style: "width: 75px;", id: "odr_type_#{index}", data_live_search: "true"}%>
        <p></p>
          <%= text_field_tag "odr_date_#{index}", '', type: 'date',placeholder: 'ODR Date', id: "odr_date_#{index}", class: 'form-control input-md', style: "width: 160px; font-size:16px;"%>
        </td>
        <td>
          <%= text_field_tag "release_time_#{index}", '', type: 'time',placeholder: 'placement Date', id: "release_time_#{index}", class: 'form-control input-md', required: true, style: "width: 160px; font-size:16px;"%>
        <p></p>
          <%= text_field_tag "release_date_#{index}", '', type: 'date',placeholder: 'placement Date', id: "release_date_#{index}", class: 'form-control input-md release_date',required: true, style: "width: 160px; font-size:16px;"%>
        </td>
        <td>
          <%= text_area_tag "remarks_#{index}", '', placeholder: 'enter remarks if any', id: "remarks_#{index}", class: 'form-control input-md', style: "width: 155px; height:80px;"%>
          <%= hidden_field_tag  "record_id_#{index}", "", id: "record_id_#{index}" %>
          
        </td>
        <td align="center">
          <a href="#" class="remove-ip label label-danger" id="<%= index %>-other-load_delete" style="padding: 20%"><i class="fa fa-trash-o"></i></a>          
        </td>
        
      </tr>    
    <%end%>  
  </tbody>
</table>
  <div class= "form-group station_error_msg" id="station_error_msg" style="display: none"></div>
  <%= hidden_field_tag  "date", "", id: "date" %>
  <input type="button" class="btn btn-success btn-flat fa-input" value="&#xf067;&nbsp;&nbsp;Add Row" id="other_load_add">
  <div class="modal-footer" style="text-align: center !important;">
    <button class="btn btn-primary btn-flat submit" type="submit"><i class="fa fa-check submit"></i>Save</button>
  </div>   
  <% end %>
</div>

<div class="modal fade colored-header" id="delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" style="width: 350px;">
    <div class="modal-content">
      <div class="modal-header">
        <h3>You really want to delete this Row?</h3>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body" align="center">
        
          <input type="button" class="btn btn-danger btn-lg" value="Delete" id="confirm_other_load_delete">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <input type="button" class="btn btn-default btn-lg" data-dismiss="modal" value="Cancel"id="cancel">
     
     </div>
    </div>
  </div>
</div>

<script >
$(function(){

  $('table tr').each(function(index) {
    $(this).find('td:nth-child(1)').html(index-1+1);
  });

  $(document).ready(function(){
    $('.release_date').each(function(i) {
      var row_no = $(this).attr('id').split('_')[2]
      var release_date_id = "#release_date_"+row_no
      var mydate = $("#datepicker").val();
      var parts = mydate.split('/');
      var set_release_date = parts[2] + '-' + parts[1] + '-' + parts[0];
      $(release_date_id).attr("max", set_release_date);
      $(release_date_id).attr("min", set_release_date);
    });  
  });

  <% (0..25).each_with_index do |no,index| %>
    <%if index >= (@other_loads.count || 0)%>
      var tr = '<%=".other_load_row_#{index}"%>';
      $(tr).hide();
    <%end%> 
  <% end %>
   <%if @other_loads.present?%>
      <%@other_loads.each_with_index do |data,index|%>
          from_station = "#from_station_"+<%=index%>
          to_station = "#to_station_"+<%=index%>
          loaded_unit = "#loaded_unit_"+<%=index%>
          rake_count = "#rake_count_"+<%=index%>
          major_commodity = "#major_commodity_"+<%=index%>
          wagon_type = "#wagon_type_"+<%=index%>
          gross_tons ="#gross_tons_"+<%=index%>
          net_tons =  "#net_tons_"+<%=index%>
          odr_type = "#odr_type_"+<%=index%>
          odr_date = "#odr_date_"+<%=index%>
          release_time = "#release_time_"+<%=index%>
          release_date = "#release_date_"+<%=index%>
          remarks = "#remarks_"+<%=index%>
          rake_id = "#record_id_"+<%=index%>

          $(from_station).val('<%=Station.where(id: LoadUnload.where(id: data.load_unload_id).pluck(:station_id)[0]).pluck(:code)[0]%>');
          $(to_station).val('<%=Station.where(id: data.station_id).pluck(:code)[0]%>');
          $(loaded_unit).val('<%=data.loaded_unit%>');
          $(rake_count).val('<%=data.rake_count%>');
          $(major_commodity).val('<%=data.major_commodity_id%>');
          $(wagon_type).val('<%=data.wagon_type_id%>');
          $(gross_tons).val('<%=data.gross_tons%>');
          $(net_tons).val('<%=data.net_tons%>');
          $(odr_type).val('<%=data.odr_type%>');
          $(odr_date).val('<%=data.odr_date%>');
          $(release_time).val('<%=data.release_time%>');
          $(release_date).val('<%=data.release_date%>');
          $(remarks).val('<%=data.remark%>');
          $(rake_id).val('<%=data.id%>');
          
      <%end%>
    <%end%>

  $("#other_load_add").click(function(){
    $(".other-row-data:hidden").each(function(i){
      if (i==0) {
        $(this).show();
      }
    });
  });

  $(".submit").click(function () {
    $("#date").val($("#datepicker").val());
    $(".other-row-data:hidden").each(function(i) {
      $(this).remove('');
    });
  });
  
  $('#other-loading-form').submit(function(){
    $("button[type='submit']", this)
      .text("Please Wait...")
      .attr('disabled', 'disabled');
    return true;
  });

  $(".label-danger").on('click',function(){
    delete_index = $(this).attr('id').split("-")[0];
    delete_other_load_id = $("#record_id_"+delete_index).val();
    var visible_row_count = 0
    
    $('.other-load-tr:visible').each(function() {
      visible_row_count = visible_row_count + 1
    });
    
    $("#delete-modal").modal('show');
   

  });

  $("#confirm_other_load_delete").click(function () {
    $("#delete-modal").modal('hide');

    if (delete_other_load_id != "") {
          $.ajax({
          type: "get",
          url: "/delete_other_load.js?delete_other_load_id=" + delete_other_load_id
        });
      }

     $('.other-load-tr:visible').each(function() {
      if($(this).attr("id").split("_")[4] == delete_index){
        $(this).remove('');
      }
    });
  });


 
});

   // Finds From station
    $('.from_station').on('focusout', function () {
    
    var row_no = $(this).attr('id').split('_')[2]
    var from_station_id = "from_station_"+row_no

    var from_station_code = $(this).val();
    // debugger
      if (from_station_code != "") {
          $.ajax({
          type: "get",
          url: "/find_from_station_other_loads.js?from_station_code=" + from_station_code + "&from_station_id=" + from_station_id
        });
      }
    
    });
    // Finds to station
   $('.to_station').on('focusout', function () {
    
    var row_no = $(this).attr('id').split('_')[2]
    var to_station_id = "to_station_"+row_no

    var station_code = $(this).val();
      if (station_code != "") {
          $.ajax({
          type: "get",
          url: "/find_to_station_other_loads.js?station_code=" + station_code + "&to_station_id=" + to_station_id
        });
      }
    
    });

</script>

app/views/admin/other_loads/_other_load_new.html.erb
<div class="tab-container" id="other_load_form">
  <div class="tab-content" >
    <%= render 'form' %>
  </div>
</div>

app/views/admin/other_loads/create.js.erb
$("#other_load_form").remove('');
$("#other_load_new_form").html('<%= j render 'other_load_new'%>');

app/views/admin/other_loads/find_from_station_other_loads.js.erb
var from_station = "#<%=@from_station%>"
<%if(@stn == false)%>

  var error_msg ="----From Station not found"
  $("#station_error_msg").text(error_msg).css({'color': 'red', 'background-color': 'yellow', 'width':'170px'});
  $(".station_error_msg").show();
  $(from_station).focus(); 
  
<%else%>
  $("#station_error_msg").text("");
  $(".station_error_msg").hide();
<%end%>

app/views/admin/other_loads/find_to_station_other_loads.js.erb
var to_station = "#<%=@to_station%>"
<%if(@stn == false)%>

  var error_msg ="-----To Station not found"
  $("#station_error_msg").text(error_msg).css({'color': 'red', 'background-color': 'yellow', 'width':'170px'});
  $(".station_error_msg").show();
  $(to_station).focus(); 
<%else%>
 $(".station_error_msg").hide();
<%end%>

app/views/admin/other_loads/new.html.erb
<script>

    $(document).ready(function () {
      $('.loading-remain-open').click();
    });

</script>
<style>
  .modal-dialog {
      margin: 30px auto;
      width: 80%;
  }
  .add-cursor tr{
   height: 5px;
  }  
  .table.table-dark tbody td {
    padding: 5px;

  }

.add-cursor {cursor: pointer;}
.add-cursor span {cursor: pointer;display: inline-block;position: relative;transition: 0.5s;}
/*.tax-and-statutory-settings-hide-show span:after {content: '»';position: absolute;opacity: 0;top: 0;right: -20px;transition: 0.5s;}
.tax-and-statutory-settings-hide-show span {padding-right: 25px;}
.tax-and-statutory-settings-hide-show:hover span:after {opacity: 1;right: 0;}*/
.input-group .form-control {
    float: right;
    width: 35%;
  }
  html {
    overflow-x: scroll;
  }

  select.set-dropdown {
    display: block !important;
    opacity: 0;
    height: 0px;
  }
  table th, table td { overflow: hidden; }
  
  
</style>


<% @method = params[:id].present? ? "PATCH" : "POST" %>
<% @url = params[:id].present? ? admin_other_load_path(params[:id]) : admin_other_loads_path %>
<%@header = ["From/Station","To/Station","Forecast Date","Received/As","Loaded/Total Units","Wagon Type","Rake Count","Commodity","Stack (CONT)","ARR Date","ARR Time","PM Time","PM Date","RL Time","RL Date","Action"]%>


<div class="table-responsive main-client-ldng" >
  <div id="client-message"></div>
  <table class="table hover table-dark" id="other_load-ldng">
    <caption>
      <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" >
          <span class="pull-left lead-text">
            Other Loading :<%=(@total_other_loads)%>
          </span>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
        <%= text_field_tag "other_load_date", Date.today.strftime('%Y-%m-%d'),placeholder: 'other load date', id: "datepicker", class: 'form-control input_class'%>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
        <button class="btn btn-primary btn-flat submit" id="submit_data" type="submit">Display</button>
      </div>
  </caption>
  </table>
  </div>


<div id="other_load_new_form"></div>
<script>
  var old_date = '<%=Date.today.strftime("%d/%m/%Y")%>';
  $(function () {
    $("#datepicker").datepicker({ 
          autoclose: true, 
          format:"dd/mm/yyyy",
          todayHighlight: true,
    });

    $("#datepicker").on("change",function(){
      $("#other_load_new_form").empty();
    });

    $('#datepicker').datepicker('setDate', 'today');
    
  });
  $(".submit").click(function () {
      effective_from = $("#datepicker").val();
      
        $.ajax({
          type: "get",
          url: "/admin/other_loads/new.js?data=" + effective_from

        });
        old_date = effective_from 
      
  });
  

</script>

app/views/admin/other_loads/new.js.erb
$("#other_load_form").remove('');
$("#other_load_new_form").html('<%= j render 'other_load_new'%>');