config/routes.rb
Rails.application.routes.draw do
	
  
  #devise_for :models
  devise_for :users
  root :to => 'home#index'
  
  

  match '/get_division', controller: 'admin/areas', action: 'get_division', via: [:get], as: 'get_division'
  
  match '/find_station', controller: 'admin/rake_loads', action: 'find_station', via: [:get], as: 'find_station'
  match '/find_from_station', controller: 'admin/rake_loads', action: 'find_from_station', via: [:get], as: 'find_from_station'
  match '/delete_rake_load', controller: 'admin/rake_loads', action: 'delete_rake_load', via: [:get], as: 'delete_rake_load'
  
  match '/find_to_station_other_loads', controller: 'admin/other_loads', action: 'find_to_station_other_loads', via: [:get], as: 'find_to_station_other_loads'
  match '/find_from_station_other_loads', controller: 'admin/other_loads', action: 'find_from_station_other_loads', via: [:get], as: 'find_from_station_other_loads'
  match '/delete_other_load', controller: 'admin/other_loads', action: 'delete_other_load', via: [:get], as: 'delete_other_load'
  
  match '/load_commodity_breakup', controller: 'admin/one_rake_loads', action: 'load_commodity_breakup', via: [:get], as: 'load_commodity_breakup'
  match '/delete_rake_commodity_breakup', controller: 'admin/one_rake_loads', action: 'delete_rake_commodity_breakup', via: [:get], as: 'delete_rake_commodity_breakup'  

  match '/unload_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'unload_commodity_breakup', via: [:get], as: 'unload_commodity_breakup'
  match '/delete_unload_rake_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'delete_unload_rake_commodity_breakup', via: [:get], as: 'delete_unload_rake_commodity_breakup'

  match '/find_station_unloads', controller: 'admin/rake_unloads', action: 'find_station_unloads', via: [:get], as: 'find_station_unloads'
  match '/find_from_station_unloads', controller: 'admin/rake_unloads', action: 'find_from_station_unloads', via: [:get], as: 'find_from_station_unloads'
  match '/delete_rake_unload', controller: 'admin/rake_unloads', action: 'delete_rake_unload', via: [:get], as: 'delete_rake_unload'
  
  match '/find_to_station_other_unloads', controller: 'admin/other_unloads', action: 'find_to_station_other_unloads', via: [:get], as: 'find_to_station_other_unloads'
  match '/find_from_station_other_unloads', controller: 'admin/other_unloads', action: 'find_from_station_other_unloads', via: [:get], as: 'find_from_station_other_unloads'
  match '/delete_other_unload', controller: 'admin/other_unloads', action: 'delete_other_unload', via: [:get], as: 'delete_other_unload'
  

  match '/find_to_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_to_station_gets_unloads', via: [:get], as: 'find_to_station_gets_unloads'
  match '/find_from_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_from_station_gets_unloads', via: [:get], as: 'find_from_station_gets_unloads'
  match '/delete_gets_unload', controller: 'admin/gets_unloads', action: 'delete_gets_unload', via: [:get], as: 'delete_gets_unload'
  
  match '/find_to_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_to_station_aecs_unloads', via: [:get], as: 'find_to_station_aecs_unloads'
  match '/find_from_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_from_station_aecs_unloads', via: [:get], as: 'find_from_station_aecs_unloads'
  match '/delete_aecs_unload', controller: 'admin/aecs_unloads', action: 'delete_aecs_unload', via: [:get], as: 'delete_aecs_unload'

  match '/delete_load_interchange', controller: 'admin/load_interchanges', action: 'delete_load_interchange', via: [:get], as: 'delete_load_interchange'
  match '/delete_crack_rake', controller: 'admin/crack_rakes', action: 'delete_crack_rake', via: [:get], as: 'delete_crack_rake'
  
  match '/delete_allowance', controller: 'admin/allowances', action: 'delete_allowance', via: [:get], as: 'delete_allowance'
  
  match '/delete_employee_allowance', controller: 'admin/employee_allowances', action: 'delete_employee_allowance', via: [:get], as: 'delete_employee_allowance'
  
  match '/delete_employee', controller: 'admin/employees', action: 'delete_employee', via: [:get], as: 'delete_employee'
  match '/delete_employee_category_detail', controller: 'admin/employees', action: 'delete_employee_category_detail', via: [:get], as: 'delete_employee_category_detail'
  match '/delete_employee_transfer_detail', controller: 'admin/employees', action: 'delete_employee_transfer_detail', via: [:get], as: 'delete_employee_transfer_detail'
  match '/delete_employee_training_detail', controller: 'admin/employees', action: 'delete_employee_training_detail', via: [:get], as: 'delete_employee_training_detail'
  match '/delete_employee_medical_detail', controller: 'admin/employees', action: 'delete_employee_medical_detail', via: [:get], as: 'delete_employee_medical_detail'
  match '/delete_employee_dar_detail', controller: 'admin/employees', action: 'delete_employee_dar_detail', via: [:get], as: 'delete_employee_dar_detail'
  match '/delete_employee_award_detail', controller: 'admin/employees', action: 'delete_employee_award_detail', via: [:get], as: 'delete_employee_award_detail'
  match '/find_employee_number', controller: 'admin/employees', action: 'find_employee_number', via: [:get], as: 'find_employee_number'
  
  match '/delete_employee_cadre', controller: 'admin/employee_cadres', action: 'delete_employee_cadre', via: [:get], as: 'delete_employee_cadre'
  

  #--------------Excel Reports Download Starts-----------------
  match '/rake_load_excel_download', controller: 'admin/loading_reports', action: 'rake_load_excel_download', via: [:get], as: 'rake_load_excel_download'
  match '/custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'custom_load_report_excel_download', via: [:get], as: 'custom_load_report_excel_download'
  match '/month_custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'month_custom_load_report_excel_download', via: [:get], as: 'month_custom_load_report_excel_download'
  match '/excel_reports_download', controller: 'admin/excel_reports', action: 'excel_reports_download', via: [:get], as: 'excel_reports_download'
  

  #--------------Excel Reports Download Ends-----------------

  #--------------PDF Reports Download Starts-----------------
  match '/download_summary_pdf', controller: 'admin/loading_reports', action: 'download_summary_pdf', via: [:get], as: 'download_summary_pdf'
  match '/abc_unload_summary_pdf', controller: 'admin/unloading_reports', action: 'abc_unload_summary_pdf', via: [:get], as: 'abc_unload_summary_pdf'
  #--------------PDF Reports Download Ends-----------------

  namespace :admin do
  	resources :railway_zones,:states,:divisions, :areas,:stations,:rake_commodities,:major_commodities, :wagon_types, :load_unloads, :rake_loads, :rake_unloads, :other_loads, :one_rake_loads, :two_rake_loads, :one_rake_unloads, :other_unloads, :gets_unloads, :aecs_unloads, :short_routes, :ic_divisions, :users, :user_roles, :loading_reports,:unloading_reports, :phasewise_reports, :one_loading_reports, :one_unloading_reports, :custom_reports, :one_custom_reports, :custom_load_reports, :month_rake_loads, :two_custom_reports, :load_interchanges, :excel_reports, :crack_rakes, :daks, :ti_positions, :allowances, :employees, :employee_cadres, :employee_allowances, :station_datas
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/state.rb
class State < ApplicationRecord

  has_many :stations



  def self.set_state_upload(params)
    
    upload_file = params[:state_attachment] 
    if upload_file.present?
      today = Date.today
      random_string = SecureRandom.hex
      File.open("public/report_content_#{random_string}.xls", 'wb') { |f| f.write(upload_file.read) }
      extra_params = [upload_file.original_filename, upload_file.path]
      spreadsheet = ApplicationController.new.open_spreadsheet(extra_params[0], extra_params[1]) rescue nil
      if spreadsheet.nil? or spreadsheet.include?("Unknown file type:")
        result = {['NA', 'NA', 'NA', 'NA'] => "#{spreadsheet}"}
      else
        result = self.state_upload(spreadsheet)
        
      end

    else
    end
  end

  def self.state_upload(sheet)
    
    sheet.each_with_index do |row, index|
      next if index == 0
      sr_no = row[0] 
      name = row[1] 
      code = row[2]
      alternative_code = row[3]
      
      State.create(name: name,code: code)
    end 
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
	before_action :set_state, only: ['show','edit','update','destroy']
	layout "admin/application"

	def index
		@states = State.all
    @states = @states.paginate(:page => (params[:page] || 1), :per_page => 20)
		respond_to do |format|
      format.html
      format.js 
    end
	end

	def new
		@state = State.new
    respond_to do |format|
      format.js
    end
    
	end

	def create
		if params[:state_attachment].present?
      State.set_state_upload(params) 
      respond_to do |format|
        format.js
      end
      
    else

      @state = State.new(state_params)
  		@state.save if @state
  		respond_to do |format|
        format.js
      end
    end

	end

	def show
		respond_to do |format|
      format.js
    end
	end

	def edit
    
		respond_to do |format|
      format.js
    end
	end

	def update
		@state.update_attributes(state_params)
		respond_to do |format|
      format.js
    end
	end

	def destroy
		@state.delete if @state
		respond_to do |format|
      format.js
    end
	end

	private

	def state_params
    params.require(:state).permit!
  end

	def set_state
		@state = State.find(params[:id])
	end

end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper

   
end

app/views/admin/states/_form.html.erb
<style>
  
  
</style>




<% input_class = (action_name == 'initial_setup') ? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup') ? 'btn-lg' : 'btn-md' %>
<% @method = params[:id].present? ? "PATCH" : "POST" %>

<% @url = params[:id].present? ? admin_state_path(params[:id]) : admin_states_path() %>
<%= form_for(@state, url: @url,class: 'form-horizontal group-border-dashed', id: 'state-form', remote: true) do |f| %>
  <div class="form-group">
    <h4 class="no-margin">Name<span style="color:red;"> *</span></h4>
    <%= f.text_field :name, class: 'form-control input-md' %>
  </div>
    
    
    <div class="form-group">
      <h4 class="no-margin">Code<span style="color:red;"> *</span></h4>
      <%= f.text_field :code,class: 'form-control input-md' %>
      
    </div>
    
    <div class="modal-footer" style="text-align: center !important;">
      <a class="btn btn-default btn-flat cancel-btn <%= btn_class %>" data-dismiss="modal" id="cancel-btn"><i class="fa fa-remove"></i>
        Cancel</a>
      <%= f.button '<i class="fa fa-check"></i>&nbsp;Save'.html_safe, style: "font-size: 14px !important;", class: 'btn btn-primary btn-flat', id: 'submit' %>
     
    </div>
<% end %>

app/views/admin/states/_import_export.html.erb
<style>
  
  
</style>


<% input_class = (action_name == 'initial_setup') ? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup') ? 'btn-lg' : 'btn-md' %>
<% @method = params[:id].present? ? "PATCH" : "POST" %>

<% @url = params[:id].present? ? admin_state_path(params[:id]) : admin_states_path() %>
 <%= form_tag(@url, method: @method, class: 'form-horizontal group-border-dashed', remote: true) do |form| %>

  <div class="form-group">
    <h4 class="no-margin">Name<span style="color:red;"> *</span></h4>
    <%= file_field_tag "state_attachment", placeholder: "Attachment", class: 'form-control input-md attachment-blank',required: true, id: "state_attachment",accept: ".xls,.xlsx,.csv",style: "width: 300px;border: 1px solid #888;" %>
  </div>
  <p>Upload only .xls, .xlsx or .csv type</p>
  <div class="modal-footer" style="text-align: center !important;">
      <a class="btn btn-default btn-flat cancel-btn <%= btn_class %>" data-dismiss="modal" id="cancel-btn"><i class="fa fa-remove"></i>
        Cancel</a>
      <button class="btn btn-primary btn-flat upload" type="submit"><i class="fa fa-upload upload"></i>Upload</button>
     
  </div>
<%end%> 

app/views/admin/states/_listing.html.erb
<tr id=<%=state.id.to_s%>>
  <td class="text-center"><span class="view-location-<%= index %>"><%= state.name rescue '' %></span></td>
  <td class="text-center"><span class="view-location-<%= index %>"><%= state.code rescue '' %></span></td>
  <%if is_viewable%>
	  <td class="text-center" style="white-space: nowrap">
	    <span class="view-location-<%= index %>">
	      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_state_path(state), :remote => true, class: "label label-default", title: "Edit State" %>
	      <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, "javascript:;", class: 'label label-danger state-delete', data: {toggle: "modal", method_type: "delete", link: admin_state_path(state.id), message: "You really want to delete this State?", target: "#custom-confirm-box"}, remote: true, title: "Delete State" %>
		  </span>
	  </td>
	<%end%>
</tr>
     

app/views/admin/states/_new_form.html.erb
<style>
  .red {
    background-color: red;
  }

  /*.lead-radio {
    font-size: 14px;
  }*/
</style>
<% input_class = (action_name == 'initial_setup')? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup')? 'btn-lg' : 'btn-md' %>

<div class="modal fade colored-header" id="add-state" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <%if params[:action].present? and params[:import_export] == "true"%>
          
            <h3>Import Data through Excel</h3>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'import_export' %>
            </div>
          
  
          <%elsif params[:action] == "edit"%>
            <h3>Edit State</h3>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'form' %>
            </div>
          <%else%>
            <h3>Add New State</h3>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'form' %>
            </div>
          <%end%>





    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/admin/states/create.js.erb
<%if @state%>
$("#state-listing").prepend("<%= j render partial: 'listing', locals: {:state => @state,:index => (50..500).to_a.sample} %>");
<%end%>
$('#add-state').find('.close').click();

app/views/admin/states/destroy.js.erb
<%if @state%>
var id = "#<%=@state.id%>"
$(id).remove('');
<%end%>

app/views/admin/states/edit.js.erb
$('#state-popup').html('<%= j render 'new_form'%>');
$('#add-state').modal('show');

app/views/admin/states/import_export.js.erb
$('#add-state').html('<%= j render partial: 'listing', :locals => {:state => state, :index => index} %>');
$('#add-state').find('.close').click();

app/views/admin/states/index.html.erb
<script>

    $(document).ready(function () {
      $('.admin-remain-open').click();
    });

</script>
<div class="table-responsive main-client-listing">
  <div id="client-message"></div>
  <table class="table hover table-dark" id="state-listing">
    <caption>
      <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <span class="pull-left lead-text">
            <%="State : #{@states.count} "%>
          </span>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input aria-invalid="false" aria-required="true" class="form-control input-md valid " type="text" id="primary-search" placeholder="Search by name or Code">
        </div>
      </div>
      <%if is_viewable%>
       <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
          <%= link_to '<i class="fa fa-plus"></i>&nbsp;&nbsp;Add state'.html_safe, new_admin_state_path, remote: true, class: "btn btn-primary btn-block btn-rad", style: "height: 35px;padding: 7px 11px" %>
          
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
          <%= link_to '<i class="fa fa-plus"></i>&nbsp;&nbsp;Import/Export'.html_safe, new_admin_state_path(import_export: "true"), remote: true, class: "btn btn-primary btn-block btn-rad", style: "height: 35px;padding: 7px 11px" %>
          
        </div>
      <%end%>
      <% if false %>
          <div class="row">
            <a href="#" class="advance-search col-md-2 pull-right" style="border-bottom: 0px;">
              <p class="filter-link">Show Advanced Search</p>
            </a>
          </div>
          <%= render 'filters' %>
      <% end %>
    </caption>
    <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <%if is_viewable%>
        <th>Actions</th>
      <%end%>
    </tr>
    </thead>
    <tbody>
      <% @states.each_with_index do |state, index| %>
        <%= render :partial => 'listing', :locals => {:state => state, :index => index} %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row no-margin no-margin">

  <div class="col-md-6 col-md-offset-4" id="com-pagination"><%= will_paginate @states, renderer: BootstrapPagination::Rails %></div>
  
</div>

<div id="state-popup"></div>


<script>
  $('.state-delete').on('click', function () {
    $('#custom-confirm-box').find('.delete').attr("data-remote", true);
  });
</script>

app/views/admin/states/new.js.erb
$('#state-popup').html('<%= j render 'new_form'%>');
$('#add-state').modal('show');

app/views/admin/states/update.js.erb
<%if @state%>
var id = "#<%=@state.id%>"
$(id).remove('');
$("#state-listing").prepend("<%= j render partial: 'listing', locals: {:state => @state,:index => (50..500).to_a.sample} %>");
<%end%>

$('#add-state').find('.close').click();