config/routes.rb
Rails.application.routes.draw do
	
  
  #devise_for :models
  devise_for :users
  root :to => 'home#index'
  
  

  match '/get_division', controller: 'admin/areas', action: 'get_division', via: [:get], as: 'get_division'
  
  match '/find_station', controller: 'admin/rake_loads', action: 'find_station', via: [:get], as: 'find_station'
  match '/find_from_station', controller: 'admin/rake_loads', action: 'find_from_station', via: [:get], as: 'find_from_station'
  match '/delete_rake_load', controller: 'admin/rake_loads', action: 'delete_rake_load', via: [:get], as: 'delete_rake_load'
  
  match '/find_to_station_other_loads', controller: 'admin/other_loads', action: 'find_to_station_other_loads', via: [:get], as: 'find_to_station_other_loads'
  match '/find_from_station_other_loads', controller: 'admin/other_loads', action: 'find_from_station_other_loads', via: [:get], as: 'find_from_station_other_loads'
  match '/delete_other_load', controller: 'admin/other_loads', action: 'delete_other_load', via: [:get], as: 'delete_other_load'
  
  match '/load_commodity_breakup', controller: 'admin/one_rake_loads', action: 'load_commodity_breakup', via: [:get], as: 'load_commodity_breakup'
  match '/delete_rake_commodity_breakup', controller: 'admin/one_rake_loads', action: 'delete_rake_commodity_breakup', via: [:get], as: 'delete_rake_commodity_breakup'  

  match '/unload_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'unload_commodity_breakup', via: [:get], as: 'unload_commodity_breakup'
  match '/delete_unload_rake_commodity_breakup', controller: 'admin/one_rake_unloads', action: 'delete_unload_rake_commodity_breakup', via: [:get], as: 'delete_unload_rake_commodity_breakup'

  match '/find_station_unloads', controller: 'admin/rake_unloads', action: 'find_station_unloads', via: [:get], as: 'find_station_unloads'
  match '/find_from_station_unloads', controller: 'admin/rake_unloads', action: 'find_from_station_unloads', via: [:get], as: 'find_from_station_unloads'
  match '/delete_rake_unload', controller: 'admin/rake_unloads', action: 'delete_rake_unload', via: [:get], as: 'delete_rake_unload'
  
  match '/find_to_station_other_unloads', controller: 'admin/other_unloads', action: 'find_to_station_other_unloads', via: [:get], as: 'find_to_station_other_unloads'
  match '/find_from_station_other_unloads', controller: 'admin/other_unloads', action: 'find_from_station_other_unloads', via: [:get], as: 'find_from_station_other_unloads'
  match '/delete_other_unload', controller: 'admin/other_unloads', action: 'delete_other_unload', via: [:get], as: 'delete_other_unload'
  

  match '/find_to_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_to_station_gets_unloads', via: [:get], as: 'find_to_station_gets_unloads'
  match '/find_from_station_gets_unloads', controller: 'admin/gets_unloads', action: 'find_from_station_gets_unloads', via: [:get], as: 'find_from_station_gets_unloads'
  match '/delete_gets_unload', controller: 'admin/gets_unloads', action: 'delete_gets_unload', via: [:get], as: 'delete_gets_unload'
  
  match '/find_to_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_to_station_aecs_unloads', via: [:get], as: 'find_to_station_aecs_unloads'
  match '/find_from_station_aecs_unloads', controller: 'admin/aecs_unloads', action: 'find_from_station_aecs_unloads', via: [:get], as: 'find_from_station_aecs_unloads'
  match '/delete_aecs_unload', controller: 'admin/aecs_unloads', action: 'delete_aecs_unload', via: [:get], as: 'delete_aecs_unload'

  match '/delete_load_interchange', controller: 'admin/load_interchanges', action: 'delete_load_interchange', via: [:get], as: 'delete_load_interchange'
  match '/delete_crack_rake', controller: 'admin/crack_rakes', action: 'delete_crack_rake', via: [:get], as: 'delete_crack_rake'
  
  match '/delete_allowance', controller: 'admin/allowances', action: 'delete_allowance', via: [:get], as: 'delete_allowance'
  
  match '/delete_employee_allowance', controller: 'admin/employee_allowances', action: 'delete_employee_allowance', via: [:get], as: 'delete_employee_allowance'
  
  match '/delete_employee', controller: 'admin/employees', action: 'delete_employee', via: [:get], as: 'delete_employee'
  match '/delete_employee_category_detail', controller: 'admin/employees', action: 'delete_employee_category_detail', via: [:get], as: 'delete_employee_category_detail'
  match '/delete_employee_transfer_detail', controller: 'admin/employees', action: 'delete_employee_transfer_detail', via: [:get], as: 'delete_employee_transfer_detail'
  match '/delete_employee_training_detail', controller: 'admin/employees', action: 'delete_employee_training_detail', via: [:get], as: 'delete_employee_training_detail'
  match '/delete_employee_medical_detail', controller: 'admin/employees', action: 'delete_employee_medical_detail', via: [:get], as: 'delete_employee_medical_detail'
  match '/delete_employee_dar_detail', controller: 'admin/employees', action: 'delete_employee_dar_detail', via: [:get], as: 'delete_employee_dar_detail'
  match '/delete_employee_award_detail', controller: 'admin/employees', action: 'delete_employee_award_detail', via: [:get], as: 'delete_employee_award_detail'
  match '/find_employee_number', controller: 'admin/employees', action: 'find_employee_number', via: [:get], as: 'find_employee_number'
  
  match '/delete_employee_cadre', controller: 'admin/employee_cadres', action: 'delete_employee_cadre', via: [:get], as: 'delete_employee_cadre'
  

  #--------------Excel Reports Download Starts-----------------
  match '/rake_load_excel_download', controller: 'admin/loading_reports', action: 'rake_load_excel_download', via: [:get], as: 'rake_load_excel_download'
  match '/custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'custom_load_report_excel_download', via: [:get], as: 'custom_load_report_excel_download'
  match '/month_custom_load_report_excel_download', controller: 'admin/custom_load_reports', action: 'month_custom_load_report_excel_download', via: [:get], as: 'month_custom_load_report_excel_download'
  match '/excel_reports_download', controller: 'admin/excel_reports', action: 'excel_reports_download', via: [:get], as: 'excel_reports_download'
  

  #--------------Excel Reports Download Ends-----------------

  #--------------PDF Reports Download Starts-----------------
  match '/download_summary_pdf', controller: 'admin/loading_reports', action: 'download_summary_pdf', via: [:get], as: 'download_summary_pdf'
  match '/abc_unload_summary_pdf', controller: 'admin/unloading_reports', action: 'abc_unload_summary_pdf', via: [:get], as: 'abc_unload_summary_pdf'
  #--------------PDF Reports Download Ends-----------------

  namespace :admin do
  	resources :railway_zones,:states,:divisions, :areas,:stations,:rake_commodities,:major_commodities, :wagon_types, :load_unloads, :rake_loads, :rake_unloads, :other_loads, :one_rake_loads, :two_rake_loads, :one_rake_unloads, :other_unloads, :gets_unloads, :aecs_unloads, :short_routes, :ic_divisions, :users, :user_roles, :loading_reports,:unloading_reports, :phasewise_reports, :one_loading_reports, :one_unloading_reports, :custom_reports, :one_custom_reports, :custom_load_reports, :month_rake_loads, :two_custom_reports, :load_interchanges, :excel_reports, :crack_rakes, :daks, :ti_positions, :allowances, :employees, :employee_cadres, :employee_allowances, :station_datas
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/major_commodity.rb
class MajorCommodity < ApplicationRecord
  has_many :rake_commodities
  has_many :rake_loads
  has_many :month_rake_loads
  has_many :rake_unloads

    def self.set_major_commodity_upload(params)
    
    upload_file = params[:major_commodity_attachment] 
    if upload_file.present?
      today = Date.today
      random_string = SecureRandom.hex
      File.open("public/report_content_#{random_string}.xls", 'wb') { |f| f.write(upload_file.read) }
      extra_params = [upload_file.original_filename, upload_file.path]
      spreadsheet = ApplicationController.new.open_spreadsheet(extra_params[0], extra_params[1]) rescue nil
      if spreadsheet.nil? or spreadsheet.include?("Unknown file type:")
        result = {['NA', 'NA', 'NA', 'NA'] => "#{spreadsheet}"}
      else
        result = self.major_commodity_upload(spreadsheet)
        
      end

    else
    end
  end

  def self.major_commodity_upload(sheet)
    
    sheet.each_with_index do |row, index|
      next if index == 0
      sr_no = row[0] 
      major_commodity = row[1] 
      name = row[2]
      
      
      MajorCommodity.create(major_commodity: major_commodity,name: name)
    end 
  end
end

app/controllers/admin/major_commodities_controller.rb
class Admin::MajorCommoditiesController < ApplicationController
  before_action :set_major_commodity, only: ['show','edit','update','destroy']
  layout "admin/application"

  def index
    @major_commodities = MajorCommodity.all
    @major_commodities = @major_commodities.paginate(:page => (params[:page] || 1), :per_page => 20)
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def new
    @major_commodity = MajorCommodity.new
    respond_to do |format|
      format.js
    end
    
  end

  def create
    if params[:major_commodity_attachment].present?
      MajorCommodity.set_major_commodity_upload(params) 
      respond_to do |format|
        format.js
      end
      
    else

      @major_commodity = MajorCommodity.new(major_commodity_params)
      @major_commodity.save if @major_commodity
      respond_to do |format|
        format.js
      end
    end

  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def edit
    
    respond_to do |format|
      format.js
    end
  end

  def update
    @major_commodity.update_attributes(major_commodity_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @major_commodity.delete if @major_commodity
    respond_to do |format|
      format.js
    end
  end

  private

  def major_commodity_params
    params.require(:major_commodity).permit!
  end

  def set_major_commodity
    @major_commodity = MajorCommodity.find(params[:id])
  end

end

app/controllers/admin/major_commodity_controller.rb
class Admin::MajorCommodityController < ApplicationController
end

app/helpers/admin/major_commodities_helper.rb
module Admin::MajorCommoditiesHelper
end

app/helpers/admin/major_commodity_helper.rb
module Admin::MajorCommodityHelper
end

app/views/admin/major_commodity/_form.html.erb
<style>
  
  
</style>




<% input_class = (action_name == 'initial_setup') ? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup') ? 'btn-lg' : 'btn-md' %>
<% @method = params[:id].present? ? "PATCH" : "POST" %>

<% @url = params[:id].present? ? admin_division_path(params[:id]) : admin_major_comodities_path() %>
<%= form_for(@division, url: @url,class: 'form-horizontal group-border-dashed', id: 'division-form', remote: true) do |f| %>
  <div class="form-group">
    <h4 class="no-margin">Name<span style="color:red;"> *</span></h4>
    <%= f.text_field :name, class: 'form-control input-md' %>
  </div>
    
    
  <div class="form-group">
    <h4 class="no-margin">Code<span style="color:red;"> *</span></h4>
    <%= f.text_field :code,class: 'form-control input-md' %>
    
  </div>
    
  <div class="form-group">
    <h4 class="no-margin">Zone Headquarter<span style="color:red;"> *</span></h4>
    <%selecte_id = @division.railway_zone_id rescue ""%>
    <%= f.select :railway_zone_id, @railway_zone = RailwayZone.all.map{|railway_zone|[railway_zone.name,railway_zone.id.to_s]}, {selected: selecte_id}, {required: true, class: 'form-control editing-family input-md'}%>
    
  </div>
    
   
    <div class="modal-footer" style="text-align: center !important;">
      <a class="btn btn-default btn-flat cancel-btn <%= btn_class %>" data-dismiss="modal" id="cancel-btn"><i class="fa fa-remove"></i>
        Cancel</a>
      <%= f.button '<i class="fa fa-check"></i>&nbsp;Save'.html_safe, style: "font-size: 14px !important;", class: 'btn btn-primary btn-flat', id: 'submit' %>
     
    </div>
<% end %>

app/views/admin/major_commodity/_import_export.html.erb
<style>
  
  
</style>


<% input_class = (action_name == 'initial_setup') ? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup') ? 'btn-lg' : 'btn-md' %>
<% @method = params[:id].present? ? "PATCH" : "POST" %>

<% @url = params[:id].present? ? admin_division_path(params[:id]) : admin_divisions_path() %>
 <%= form_tag(@url, method: @method, class: 'form-horizontal group-border-dashed', remote: true) do |form| %>

  <div class="form-group">
    <h4 class="no-margin">Name<span style="color:red;"> *</span></h4>
    <%= file_field_tag "division_attachment", placeholder: "Attachment", class: 'form-control input-md attachment-blank',required: true, id: "division_attachment",accept: ".xls,.xlsx,.csv",style: "width: 300px;border: 1px solid #888;" %>
  </div>
  <p>Upload only .xls, .xlsx or .csv type</p>
  <div class="modal-footer" style="text-align: center !important;">
      <a class="btn btn-default btn-flat cancel-btn <%= btn_class %>" data-dismiss="modal" id="cancel-btn"><i class="fa fa-remove"></i>
        Cancel</a>
      <button class="btn btn-primary btn-flat upload" type="submit"><i class="fa fa-upload upload"></i>Upload</button>
     
  </div>
<%end%> 

app/views/admin/major_commodity/_listing.html.erb
<tr id=<%=division.id.to_s%>>
  <td class="text-center"><span class="view-location-<%= index %>"><%= division.code rescue '' %></span></td>
  <td class="text-center"><span class="view-location-<%= index %>"><%= division.name rescue '' %></span></td>
  <td class="text-center"><span class="view-location-<%= index %>"><%= division.railway_zone.code rescue '' %></span></td>
  
  
  <td class="text-center" style="white-space: nowrap">
    <span class="view-location-<%= index %>">
      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_division_path(division), :remote => true, class: "label label-default", title: "Edit Division" %>
      
     

      <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, "javascript:;", class: 'label label-danger division-delete', data: {toggle: "modal", method_type: "delete", link: admin_division_path(division.id), message: "You really want to delete this Division?", target: "#custom-confirm-box"}, remote: true, title: "Delete Division" %>
    </span>
  </td>
</tr>
     

app/views/admin/major_commodity/_new_form.html.erb
<style>
  .red {
    background-color: red;
  }

  /*.lead-radio {
    font-size: 14px;
  }*/
</style>
<% input_class = (action_name == 'initial_setup')? 'input-lg' : 'input-md' %>
<% btn_class = (action_name == 'initial_setup')? 'btn-lg' : 'btn-md' %>

<div class="modal fade colored-header" id="add-division" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <%if params[:action].present? and params[:import_export] == "true"%>
          
            <h3>Import Data through Excel</h3>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'import_export' %>
            </div>
          
  
          <%elsif params[:action] == "edit"%>
            <h3>Edit Division</h3>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'form' %>
            </div>
          <%else%>
            <h3>Add New Division</h3>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <%= render 'form' %>
            </div>
          <%end%>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/admin/major_commodity/create.js.erb
<%if @division%>
$("#division-listing").prepend("<%= j render partial: 'listing', locals: {:division => @division,:index => (100..500).to_a.sample} %>");
<%end%>
$('#add-division').find('.close').click();

app/views/admin/major_commodity/destroy.js.erb
<%if @division%>
var id = "#<%=@division.id%>"
$(id).remove('');
<%end%>

app/views/admin/major_commodity/edit.js.erb
$('#division-popup').html('<%= j render 'new_form'%>');
$('#add-division').modal('show');

app/views/admin/major_commodity/import_export.js.erb
$('#add-division').find('.close').click();

app/views/admin/major_commodity/index.html.erb
<script>

    $(document).ready(function () {
      $('.admin-remain-open').click();
    });

</script>
<div class="table-responsive main-client-listing">
  <div id="client-message"></div>
  <table class="table hover table-dark" id="division-listing">
    <caption>
      <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <span class="pull-left lead-text">
            <%="Divisions : #{@divisions.count} "%>
          </span>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input aria-invalid="false" aria-required="true" class="form-control input-md valid " type="text" id="primary-search" placeholder="Search by name or Code">
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <%= link_to '<i class="fa fa-plus"></i>&nbsp;&nbsp;Add Division'.html_safe, new_admin_division_path, remote: true, class: "btn btn-primary btn-block btn-rad", style: "height: 35px;padding: 7px 11px" %>
        
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <%= link_to '<i class="fa fa-plus"></i>&nbsp;&nbsp;Import/Export'.html_safe, new_admin_division_path(import_export: "true"), remote: true, class: "btn btn-primary btn-block btn-rad", style: "height: 35px;padding: 7px 11px" %>
        
      </div>
      <% if false %>
          <div class="row">
            <a href="#" class="advance-search col-md-2 pull-right" style="border-bottom: 0px;">
              <p class="filter-link">Show Advanced Search</p>
            </a>
          </div>
          <%= render 'filters' %>
      <% end %>
    </caption>
    <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Zone Code</th>
      
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
      <% @divisions.each_with_index do |division, index| %>
        <%= render :partial => 'listing', :locals => {:division => division, :index => index} %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row no-margin no-margin">

  <div class="col-md-6 col-md-offset-4" id="com-pagination"><%= will_paginate @divisions, renderer: BootstrapPagination::Rails %></div>
  
</div>

<div id="division-popup"></div>


<script>
  $('.division-delete').on('click', function () {
    $('#custom-confirm-box').find('.delete').attr("data-remote", true);
  });
</script>

app/views/admin/major_commodity/new.js.erb
$('#division-popup').html('<%= j render 'new_form'%>');
$('#add-division').modal('show');

app/views/admin/major_commodity/update.js.erb
<%if @division%>
var id = "#<%=@division.id%>"
$(id).remove('');
$("#division-listing").prepend("<%= j render partial: 'listing', locals: {:division => @division,:index => (100..500).to_a.sample} %>");
<%end%>
$('#add-division').find('.close').click();